export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/slug/:slug',
  PRODUCT_BY_CATEGORY: '/products/category/:categoryId',
  PRODUCT_BY_BRAND: '/products/brand/:brandId',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PAYMENT_RESULT: '/payment-result',
  MY_ORDERS: '/my-orders',
  ORDER_DETAIL: '/my-orders/:id',
  POSTS: '/posts',
  POST_DETAIL: '/posts/:id',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  CHANGE_PASSWORD: '/change-password',
  
  // ADMIN ROUTES
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_BRANDS: '/admin/brands',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_USERS: '/admin/users',
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_BANNERS: '/admin/banners',
  ADMIN_POSTS: '/admin/posts',
  ADMIN_TOPICS: '/admin/topics',
  ADMIN_MENUS: '/admin/menus',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_NOTIFICATIONS: '/admin/notifications',
};
